- name: Update Ubuntu System
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa # Modify this to point to your SSH key file

  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 5
        timeout: 500

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Perform system upgrade
      apt:
        upgrade: dist
        update_cache: yes
