- name: Update Windows Server via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    - name: Add local administrator
      win_user:
        name: Utmost1428
        password: v_T3W3isnQuqv
        state: present
        groups: Administrators
    - name: Join server to asdf.co.nz domain
      ansible.windows.win_domain_membership:
        dns_domain_name: asdf.co.nz
        #hostname: "win"
        domain_admin_password: X5959xfveS!8*fUY*NrF2Vcv^RxnM@GHq$
        domain_admin_user: admin@asdf.co.nz
        ou_path: "OU=Servers,DC=asdf,DC=co,DC=nz"
        state: domain
      register: domain_state
    #- name: Install Chocolatey
    #  win_chocolatey:
    #      name: chocolatey
    #      state: present
    - name: Install development packages with Chocolatey
      win_chocolatey:
        name:
          - git
          #- visualstudiocode
          #- python
          #- nodejs
          #- dotnetcore-sdk
        state: present
    - name: Update server
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        reboot: yes
