- name: Update Windows Server via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    #- name: Add local administrator
    #- name: Install Chocolatey
    #  win_chocolatey:
    #      name: chocolatey
    #      state: present
    - name: Install development packages with Chocolatey
      win_chocolatey:
        name:
          - git
          #- visualstudiocode
          #- python
          #- nodejs
          #- dotnetcore-sdk
