- name: Update Windows Server via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    - name: Join server to domain
      ansible.windows.win_domain_membership:
        dns_domain_name: provident.local
        domain_admin_password: "X5959xfveS!8*fUY*NrF2Vcv^RxnM@GHq$"
        domain_admin_user: admin
        ou_path: "OU=Servers,DC=provident,DC=local"
        state: domain
        overwrite: true
