- name: Add local and domain users via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    - name: Add local users
      ansible.windows.win_user:
        name: "{{ item }}"
        password: "{{ item_password }}"
        groups: Administrators
        state: present
      with_items:
        - Chris
        - Neil
        - Vivek
        - Anthony
      vars:
        item_password: oY^MekHKnZ%cr9

    - name: Add domain users to local administrators group
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - provident.local\Chris
          - provident.local\Neil
          - provident.local\Vivek
          - provident.local\Anthony
        state: present
