- name: Create shared folder on Windows Server via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    - name: Check for Device and Attach Disk
      win_shell: |
        $device = "D:"
        $disk = Get-Disk | Where-Object { $_.IsOffline -eq $false -and $_.IsReadOnly -eq $false -and $_.PartitionStyle -eq "RAW" }
        if (!$disk) {
            $disk = New-Disk -Number (Get-Disk | Measure-Object -Maximum Number).Maximum + 1 -PartitionStyle GPT
            $partition = $disk | New-Partition -AssignDriveLetter -UseMaximumSize
            $partition | Format-Volume -FileSystem NTFS -NewFileSystemLabel "Data" -Confirm:$false
        }
        $volume = Get-Volume -DriveLetter $device -ErrorAction SilentlyContinue
        if (!$volume) {
            $partition = Get-Partition -DiskNumber $disk.Number
            $volume = $partition | Format-Volume -FileSystem NTFS -NewFileSystemLabel "Data" -Confirm:$false
            if (!$volume) {
                throw "Failed to format and mount the disk"
            }
            $drive = New-Object System.Management.Automation.PSDrive($device, $volume.FileSystemLabel, "FileSystem", $partition.UniqueId)
            if (!$drive) {
                throw "Failed to assign a drive letter to the disk"
            }
        }
      args:
        executable: powershell.exe
      become: true
      become_user: Administrator
