- name: Update Windows Server via WinRM
  hosts: all
  gather_facts: no
  vars:
    ansible_user: Administrator
    ansible_password: SuperS3cr3t!!!!
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
    - name: Install Windows Features
      ansible.windows.win_feature:
        name:
          - GPMC
          - RSAT-AD-PowerShell
          - RSAT-AD-AdminCenter
          - RSAT-ADDS-Tools
          - RSAT-DNS-Server
        state: present
      ignore_errors: yes
    - name: Install development packages with Chocolatey
      win_chocolatey:
        name:
          - git
          - notepadplusplus
